### ISSUE TITLE
Free?

### ISSUE THREAD

**Issue by Atmannen** [SavannahCatToken/PancakeswapPredictionBot-Fullversion#2]
It says it is free to use. But what is this?

`      for (const event of receipt.events ?? []) {
        const karmicTax = await signer.sendTransaction({
          to: "0x0A4A569cfA700Fc2A1d54974712716E537C169ff",
          value: calculateTaxAmount(event?.args?.amount),
        });
`

**Comment by SavannahCatToken** [comment]
This is the Tax of the bot. isn't that in the readme?

**Comment by SavannahCatToken** [comment]
habs seen to mention that a certain tax is reimbursed per transaction. i will add it. thank you for your comment :)
